-- First make sure the table exists
CREATE TABLE IF NOT EXISTS `LABORATORY` (
  `LAB_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LAB_NAME` varchar(100) NOT NULL,
  `LAB_DESCRIPTION` text DEFAULT NULL,
  `CAPACITY` int(11) NOT NULL DEFAULT 30,
  `STATUS` enum('AVAILABLE','MAINTENANCE','OCCUPIED') NOT NULL DEFAULT 'AVAILABLE',
  `CREATED_AT` timestamp NOT NULL DEFAULT current_timestamp(),
  `UPDATED_AT` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`LAB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insert labs only if they don't already exist
INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 524', 'Computer Laboratory Room 524', 30, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 524');

INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 526', 'Computer Laboratory Room 526', 25, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 526');

INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 528', 'Computer Laboratory Room 528', 20, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 528');

INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 530', 'Computer Laboratory Room 530', 30, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 530');

INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 542', 'Computer Laboratory Room 542', 25, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 542');

INSERT INTO `LABORATORY` (`LAB_NAME`, `LAB_DESCRIPTION`, `CAPACITY`, `STATUS`)
SELECT 'Lab 544', 'Computer Laboratory Room 544', 15, 'AVAILABLE'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM `LABORATORY` WHERE `LAB_NAME` = 'Lab 544');
